name: crontab

# 触发条件
on:
  workflow_dispatch:

  schedule:
    # - cron: '0 3,12 * * *'
    # 表达式生成  https://crontab.guru/
    #- cron: '0 18 * * *'
    - cron: 0 */6 * * *

env: # 设置环境变量
  TZ: Asia/Shanghai
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: 执行任务
      run: |
        python ./utils/main.py
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./freev2
        git add ./utils
        git commit -m "更新时间 $(date '+%Y-%m-%d %H:%M:%S')"
        git push origin main
#     - name: 推送更改
#       uses:  ad-m/github-push-action@master
#       with:
#          # github_token: ${{ secrets.TOKEN }}
#          branch: main

#     - name: Single repo mirror
#       uses: Yikun/hub-mirror-action@master
#       with:
#         src: github/LiTugou
#         dst: gitee/li-tugou
#         dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#         dst_token: ${{ secrets.GITEE_TOKEN }}
#         static_list: "Crontab"
